from setuptools import setup, find_packages

setup(
    name="logistics_optimization",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.2.0",
        "scipy>=1.10.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.13.0",
        "dash>=2.9.0",
        "dash-iconify>=0.1.2",
        "python-dotenv>=1.0.0",
        "sqlalchemy>=2.0.0",
        "fastapi>=0.95.0",
        "uvicorn>=0.21.0",
        "pulp>=2.7.0",
        "openpyxl>=3.1.0",
        "xlrd>=2.0.1",
        "dash-table>=5.0.0",
        "xgboost>=2.0.0",
        "reportlab>=4.0.0",
    ],
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="A comprehensive logistics optimization system using predictive and prescriptive analytics",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
) 